apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - env:
            - name: POSTGRES_NAME
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          image: postgres
          name: db
          #volumeMounts:
            #- mountPath: /var/lib/postgresql/data
              #name: db-claim0
      restartPolicy: Always
      #volumes:
        #- name: db-claim0
          #persistentVolumeClaim:
            #claimName: db-claim0
