version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgresql/db:/var/lib/postgresql/data
  web:
    container_name: web
    build: .
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: make runserver
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
  dns:
    container_name: dns
    image: ubuntu/bind9
   #  restart: always
    environment:
      - BIND9_USER=root
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - ./dns/config:/etc/bind/
      - ./dns/cache:/var/cache/bind
      - ./dns/records:/var/lib/bind
    # command: named -c /etc/bind/named.conf -g -u named
  tests:
    build: .
    command: make test
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    profiles: ["cli-only"]

volumes:
  static: