version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./redis:/var/lib/redis
    command: redis-server --save 60 1 --loglevel warning
  web:
    build: .
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: make runserver
  tests:
    build: .
    command: make test
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    profiles: ["cli-only"]

volumes:
  redis:
  postgresql: