version: "3.8"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./django/postgresql/db:/var/lib/postgresql/data
  redis:
    image: redis
    expose:
      - 6379
    command: redis-server --save 60 1 --loglevel warning
  web:
    container_name: web
    build: 
      context: ./django
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "8000"
    env_file:
      - ./.env/dev.env
    volumes:
      - ./django/static:/usr/src/app/static
    depends_on:
      - db
      - redis
    command: make runserver
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./django/static:/usr/src/app/static
    depends_on:
      - web
  dns:
    container_name: dns
    image: ubuntu/bind9
   #  restart: always
    environment:
      - BIND9_USER=root
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - ./dns/config:/etc/bind/
      - ./dns/cache:/var/cache/bind
      - ./dns/records:/var/lib/bind
    command: named -c /etc/bind/named.conf -g
  tests:
    build: .
    command: make test
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    profiles: ["cli-only"]

volumes:
  static: