version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgresql/db:/var/lib/postgresql/data
  web:
    build: .
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: make runserver
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/html:/usr/share/nginx/html
  tests:
    build: .
    command: make test
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    profiles: ["cli-only"]

volumes:
  static: